name: Build & Test

on:
  push:
    branches: [ master, dev, docker ]
  pull_request:
    branches: [ master, dev, docker ]

jobs:
  publish-dockerhub:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Build and push image
        env:
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker build -t tdtgit/sitemap-warmer .
          docker login -u tdtgit -p $DOCKER_PASSWORD
          docker push tdtgit/sitemap-warmer --all-tags