name: Build & Test

on:
  push:
    branches: [ master, dev, docker ]
  pull_request:
    branches: [ master, dev, docker ]

jobs:
  publish-dockerhub:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push image
        env:
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm/v7 -t tdtgit/sitemap-warmer .
          docker login -u tdtgit -p $DOCKER_PASSWORD
          docker push tdtgit/sitemap-warmer --all-tags