name: Build & Test

on:
  push:
    branches: [ master, dev, docker ]
  pull_request:
    branches: [ master, dev, docker ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        node-version: [ 10.x, 12.x, 14.x, 16.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci

  test:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        node-version: [ 10.x, 12.x, 14.x, 16.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: node index.js wordpress.org
      - run: node index.js https://wordpress.org
      - run: node index.js https://wordpress.org/sitemap.xml
      - run: node index.js https://wordpress.org --quite
      - run: node index.js https://wordpress.org --range 604800
      - run: node index.js https://wordpress.org --no-css
      - run: node index.js https://wordpress.org --no-js
      - run: node index.js https://wordpress.org --no-images
      - run: node index.js https://wordpress.org --no-brotli

  publish-npm:
    if: github.ref == 'refs/heads/master'
    name: Publish to NPM
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

  publish-ghr:
    if: github.ref == 'refs/heads/master'
    needs: test
    name: Publish to Github Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set env
        run: echo "PACKAGE_VERSION=$(grep '"version"' package.json | cut -d '"' -f 4 | head -n 1)" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.PACKAGE_VERSION }}
          release_name: Release ${{ env.PACKAGE_VERSION }}
          body: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false

  publish-dockerhub:
    needs: test
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{secrets.DOCKER_USER}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    steps:
      - name: Get package version
        run: echo "PACKAGE_VERSION=$(grep '"version"' package.json | cut -d '"' -f 4 | head -n 1)" >> $GITHUB_ENV
      - name: Build and push image
        run: |
          docker build --tag tdtgit/sitemap-warmer:$PACKAGE_VERSION --tag tdtgit/sitemap-warmer:latest .
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          docker push tdtgit/sitemap-warmer:$PACKAGE_VERSION
          docker push tdtgit/sitemap-warmer:latest