name: Build & Test

on:
  push:
    branches: [ master, dev, docker ]
  pull_request:
    branches: [ master, dev, docker ]

jobs:
  publish-dockerhub:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Build and push image
        env:
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          export PACKAGE_VERSION=$(grep '"version"' package.json | cut -d '"' -f 4 | head -n 1)
          docker buildx create --use
          docker buildx build --platform linux/arm/v7,linux/arm64/v8,linux/amd64d -t tdtgit/sitemap-warmer:$PACKAGE_VERSION -t tdtgit/sitemap-warmer:latest .
          docker login -u tdtgit -p $DOCKER_PASSWORD
          docker push tdtgit/sitemap-warmer --all-tags