name: Build & Test

on:
  push:
    branches: [ master, dev, docker ]
  pull_request:
    branches: [ master, dev, docker ]

jobs:
  publish-dockerhub:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Build and push image
        env:
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker buildx build --push --platform linux/arm/v7,linux/arm64,linux/amd64 -t tdtgit/sitemap-warmer .
          docker login -u tdtgit -p $DOCKER_PASSWORD
          docker push tdtgit/sitemap-warmer --all-tags